### ISSUE TITLE
Govee Lights Local not adding device H6093

### ISSUE THREAD

**Issue by kjstanfield** [Galorhallen/govee-local-api#72]
Debug log shows this error:

```
2024-11-23 14:34:25.031 WARNING (MainThread) [homeassistant.components.govee_light_local.coordinator] Device H61E5 is not supported. Only power control is available. Please open an issue at 'https://github.com/Galorhallen/govee-local-api/issues'
2024-11-23 14:34:25.077 WARNING (MainThread) [homeassistant.components.govee_light_local.coordinator] Device H6093 is not supported. Only power control is available. Please open an issue at 'https://github.com/Galorhallen/govee-local-api/issues'
2024-11-23 14:34:25.077 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/govee_local_api/controller.py", line 326, in _handle_scan_response
    self, message.ip, fingerprint, message.sku, capabilities
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/govee_local_api/message.py", line 105, in ip
    return self._data["ip"]
           ~~~~~~~~~~^^^^^^
KeyError: 'ip'
```

I am happy with just being able to turn on/off I am just not able to get it added to be able to do that.

**Comment by Galorhallen** [comment]
The support can be added, but the KeyError is weird. Is it happening all the time? Even after an Home Assistant restart?

**Comment by kjstanfield** [comment]
Yes, if I turn debug on it just spams the log full of this error.

[home-assistant_govee_light_local_2024-11-29T00-42-55.193Z.log](https://github.com/user-attachments/files/17953152/home-assistant_govee_light_local_2024-11-29T00-42-55.193Z.log)

**Comment by kjstanfield** [comment]
This is my log after a full restart:

[home-assistant_2024-11-29T00-49-57.337Z.log](https://github.com/user-attachments/files/17953173/home-assistant_2024-11-29T00-49-57.337Z.log)

**Comment by garrit-schroeder** [comment]
Having the exact same issue with the integration and device. Support much appreciated :)
